//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAzureMob.QueryResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AzureUrlsProd {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AzureUrlsProd() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoAzureMob.QueryResource.AzureUrlsProd", typeof(AzureUrlsProd).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mkt-meli-functions.azurewebsites.net/api/MKT_MELI_QuestionBlacklist?Type={Type}&amp;UserID={UserId}&amp;BlockedUserID={BlockUserId}&amp;code=BGSQY9rhIgGrBWpKadwLYf5z0e6o%2fjE6LWi4ysWc5uJ2ZQBBKC1nZQ%3D%3D.
        /// </summary>
        public static string BlockUserFromQuestioning {
            get {
                return ResourceManager.GetString("BlockUserFromQuestioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mkt-meli-functions.azurewebsites.net/api/MKT_MELI_QuestionDelete?UserID=1117314334&amp;QuestionID=12733863381&amp;code=8Q7yRaPWGYeWJL6tfiKDOT8ydjo5D3kNwnHrOTIOTfY5FNmBxSokew%3D%3D.
        /// </summary>
        public static string DeleteQuestionById {
            get {
                return ResourceManager.GetString("DeleteQuestionById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://autoazur-create-invoice.azurewebsites.net/api/INV_CreatePreInvoice?code=KWW4qnM/VFHiD8oBalayQMMY8PVJ9Sl3OsJ4KdrEetfgJYqyxn0O7Q==.
        /// </summary>
        public static string FacrurarRemission {
            get {
                return ResourceManager.GetString("FacrurarRemission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dev-joyce.azurewebsites.net/api/INV_GetAvailableQuantity?code=4ipIiEpScvE/aG0S8PGib2DoEMXoNXgRofoh8n4BDcaNL9figHUmgA==.
        /// </summary>
        public static string GetAvailableQuantity {
            get {
                return ResourceManager.GetString("GetAvailableQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mkt-meli-functions.azurewebsites.net/api/MKT_MELI_POS_ListMessages?code=kXMkWmq84zQkhHqoYHMUgkB8S7UaJj8T967CGmMSaspkROquMnp4aw==.
        /// </summary>
        public static string GetListMessaging {
            get {
                return ResourceManager.GetString("GetListMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dev-autoazur-platform.azurewebsites.net/api/POS_PAY_GetPagoURL?code=wJpPnB06rRoimak2RvZ8ujidsNHK38Mut6mBsLYgxFb5dRBoUJeafA==.
        /// </summary>
        public static string GetPagoURL {
            get {
                return ResourceManager.GetString("GetPagoURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mkt-meli-functions.azurewebsites.net/api/MKT_MELI_QuestionBlacklist?code=BGSQY9rhIgGrBWpKadwLYf5z0e6o%2fjE6LWi4ysWc5uJ2ZQBBKC1nZQ%3D%3D.
        /// </summary>
        public static string MKT_MELI_QuestionBlacklist {
            get {
                return ResourceManager.GetString("MKT_MELI_QuestionBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://noti-autoazur.azurewebsites.net/api/NOT_GetPermissions?code=XXNH1uTRmGeR2KA7MAZTPJLuTRa6PRh6enCoH81iTBBew6taC9pCSg==.
        /// </summary>
        public static string NotifyPermission {
            get {
                return ResourceManager.GetString("NotifyPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mkt-meli-functions.azurewebsites.net/api/MKT_MELI_QuestionReply?QuestionID=12688253703&amp;Text=Es%20de%20MDF&amp;AnsweredBy=12688253703&amp;code=r2v2kkwdrRVK5w1C46h4%2fWfn6rBTZ%2fsq32NdIIyLtcanvlk8L%2fETFA%3D%3D.
        /// </summary>
        public static string PostQuestionReply {
            get {
                return ResourceManager.GetString("PostQuestionReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://autoazur-render-pdf-by-http.azurewebsites.net/api/RenderInvoicePDFV2?code=R/EjjYNVGwR0K6E1hsOUfMSkeEWItRXLJgaq6UY48iDOY436WuqkqQ==&amp;invoiceid=.
        /// </summary>
        public static string SaldoPDF {
            get {
                return ResourceManager.GetString("SaldoPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://autoazur-create-invoice.azurewebsites.net/api/INV_RenderInvoiceXML?code=q1hHLUWILgg0zcb6jpssVcNjKcayslorGCUeNwEKeNVN1O3jummtaA==.
        /// </summary>
        public static string SaldoXML {
            get {
                return ResourceManager.GetString("SaldoXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dev-joyce.azurewebsites.net/api/INV_AsignarTimbresEmisor?code=avBmmsGZBe1l09PlkqDewGTNjb7AvsL2yF7rKGo8dJgfPWuROeH7qQ==.
        /// </summary>
        public static string SaveTimberEmisor {
            get {
                return ResourceManager.GetString("SaveTimberEmisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://autoazur-invoice-functions.azurewebsites.net/api/INV_UpdateProfileRelations?code=pUEY4Y5UM4M-RmxZB7DyIgQcRza8d-0UFIf7IklkrZ3JAzFuGFJzRQ==.
        /// </summary>
        public static string SaveUserProfileRelation {
            get {
                return ResourceManager.GetString("SaveUserProfileRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mkt-meli-functions.azurewebsites.net/api/MKT_MELI_MessageReply?code=EXAe5iZmijHGeyM2pJm12IleVE4GmvqFraj/UHPj7LNGBWt/AMVtOA==.
        /// </summary>
        public static string SendMessageReply {
            get {
                return ResourceManager.GetString("SendMessageReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://noti-autoazur.azurewebsites.net/api/NOT_SavePermissions?code=Pyw8JwSVUSLzeMyRF3Ga4k62LJENqfiiH058Lsj8Ime//DmQ7ozh7Q==.
        /// </summary>
        public static string UpdatePermission {
            get {
                return ResourceManager.GetString("UpdatePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://autoazur-products.azurewebsites.net/api/PROD_MKT_UpdateSyncStockPrices?code=qwetOx/N/u0uiQa1LuNnLqMwDqN3NH8r5ass4El2/vjew4O2wPj79Q==.
        /// </summary>
        public static string UpdateSyncStockPrices {
            get {
                return ResourceManager.GetString("UpdateSyncStockPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://stoautoazurprod.blob.core.windows.net/mystorage/2f89a3b8-513d-4421-930f-a6fa9ae20ebd/Soporte/usuarios.json.
        /// </summary>
        public static string UserAccounts {
            get {
                return ResourceManager.GetString("UserAccounts", resourceCulture);
            }
        }
    }
}
