//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAzureMob.QueryResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AzureUrls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AzureUrls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoAzureMob.QueryResource.AzureUrls", typeof(AzureUrls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dev-autoazur-platform.azurewebsites.net/api/MKT_MELI_QuestionBlacklist?Type={Type}&amp;UserID={UserId}&amp;BlockedUserID={BlockUserId}&amp;code=BGSQY9rhIgGrBWpKadwLYf5z0e6o%2fjE6LWi4ysWc5uJ2ZQBBKC1nZQ%3D%3D.
        /// </summary>
        public static string BlockUserFromQuestioning {
            get {
                return ResourceManager.GetString("BlockUserFromQuestioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mkt-meli-functions.azurewebsites.net/api/MKT_MELI_QuestionDelete?code=8Q7yRaPWGYeWJL6tfiKDOT8ydjo5D3kNwnHrOTIOTfY5FNmBxSokew%3D%3D.
        /// </summary>
        public static string DeleteQuestionById {
            get {
                return ResourceManager.GetString("DeleteQuestionById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dev-autoazur-platform.azurewebsites.net/api/MOB_INV_CreatePreInvoice?code=U74MwB20SfZvVYFepIh/Fcl5hJLCv69o9w9epFaYeS68TIwFdYQxPg==.
        /// </summary>
        public static string FacrurarRemission {
            get {
                return ResourceManager.GetString("FacrurarRemission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dev-autoazur-platform.azurewebsites.net/api/INV_GetAvailableQuantity?code=RjdSFcA9vTvkPW7loazhm1IC9j2RULEOZEP8Rt30uJ2IaqBiygd7/Q==.
        /// </summary>
        public static string GetAvailableQuantity {
            get {
                return ResourceManager.GetString("GetAvailableQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dev-autoazur-platform.azurewebsites.net/api/MOB_MELI_POS_ListMessages?code=TGMWgXpDGnO/vG6/p42sqtYJYp3BE5uVO3E3He6s/e0V1pqFQ4SRlA==.
        /// </summary>
        public static string GetListMessaging {
            get {
                return ResourceManager.GetString("GetListMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dev-autoazur-platform.azurewebsites.net/api/POS_PAY_GetPagoURL?code=wJpPnB06rRoimak2RvZ8ujidsNHK38Mut6mBsLYgxFb5dRBoUJeafA==.
        /// </summary>
        public static string GetPagoURL {
            get {
                return ResourceManager.GetString("GetPagoURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mkt-meli-functions.azurewebsites.net/api/MKT_MELI_QuestionBlacklist?code=BGSQY9rhIgGrBWpKadwLYf5z0e6o%2fjE6LWi4ysWc5uJ2ZQBBKC1nZQ%3D%3D.
        /// </summary>
        public static string MKT_MELI_QuestionBlacklist {
            get {
                return ResourceManager.GetString("MKT_MELI_QuestionBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://noti-autoazur-dev.azurewebsites.net/api/NOT_GetPermissions?code=wCEaNp0rKgdPwyUaxHInsFqCuu6I4GufgnVOc7Q3NKMBiceIMzzzzA==.
        /// </summary>
        public static string NotifyPermission {
            get {
                return ResourceManager.GetString("NotifyPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dev-autoazur-platform.azurewebsites.net/api/MOB_MELI_QuestionReply?code=32W3dY/4NSHAmg8cau2vjGz9YJVV7j2fIhBAbGBcyU7EGjRpAHXtIQ==.
        /// </summary>
        public static string PostQuestionReply {
            get {
                return ResourceManager.GetString("PostQuestionReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://autoazur-render-pdf-by-http.azurewebsites.net/api/RenderInvoicePDFV2?code=R/EjjYNVGwR0K6E1hsOUfMSkeEWItRXLJgaq6UY48iDOY436WuqkqQ==&amp;invoiceid=.
        /// </summary>
        public static string SaldoPDF {
            get {
                return ResourceManager.GetString("SaldoPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://autoazur-create-invoice.azurewebsites.net/api/INV_RenderInvoiceXML?code=q1hHLUWILgg0zcb6jpssVcNjKcayslorGCUeNwEKeNVN1O3jummtaA==.
        /// </summary>
        public static string SaldoXML {
            get {
                return ResourceManager.GetString("SaldoXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dev-autoazur-platform.azurewebsites.net/api/INV_AsignarTimbresEmisor?code=pP8NGmn6Y/qKzRAGQ3AES3isGlx/rm2Nhe649QAYCJO0w3tq7hsXGQ==.
        /// </summary>
        public static string SaveTimberEmisor {
            get {
                return ResourceManager.GetString("SaveTimberEmisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://autoazur-invoice-functions-dev.azurewebsites.net/api/INV_UpdateProfileRelations?code=mANkEpz_mhK7Yofn31pgvDJF6F9svH91C2II-OnHXlCLAzFuX1rDxA==.
        /// </summary>
        public static string SaveUserProfileRelation {
            get {
                return ResourceManager.GetString("SaveUserProfileRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dev-autoazur-platform.azurewebsites.net/api/MOB_MELI_MessageReply?code=D8dyQaNwS5VWvZQvxySR8HXaEtH7edtDTiwjyZ8FighS6tJcBAXEmQ==.
        /// </summary>
        public static string SendMessageReply {
            get {
                return ResourceManager.GetString("SendMessageReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dev-autoazur-platform.azurewebsites.net/api/NOT_SavePermissions?code=4uaxHriieYnmDXanVaDzaogM0WaA3gtDkjYaim4RLpPm9OD/GJavcQ==.
        /// </summary>
        public static string UpdatePermission {
            get {
                return ResourceManager.GetString("UpdatePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dev-autoazur-platform.azurewebsites.net/api/MOB_PROD_MKT_UpdateSyncStockPrices?code=8DkYRyBKygZ0HbxQSomyT9lxprPQyRIo4/inCH7ucx1aXUbtky4qtg==.
        /// </summary>
        public static string UpdateSyncStockPrices {
            get {
                return ResourceManager.GetString("UpdateSyncStockPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://stoautoazurprod.blob.core.windows.net/mystorage/2f89a3b8-513d-4421-930f-a6fa9ae20ebd/Soporte/usuarios.json.
        /// </summary>
        public static string UserAccounts {
            get {
                return ResourceManager.GetString("UserAccounts", resourceCulture);
            }
        }
    }
}
